
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E432F052C57961215F2811FEC5ACD899'
    
_lr_action_items = {'OPEN_BRACKET':([0,3,4,14,22,23,],[3,5,3,5,5,5,]),'$end':([1,2,10,13,],[0,-2,-1,-3,]),'NEWLINE':([2,13,],[4,-3,]),'NUM':([3,5,14,15,16,22,23,],[9,11,9,18,19,9,9,]),'LABEL':([5,],[12,]),'CLOSE_BRACKET':([6,7,8,9,17,18,19,20,21,24,25,],[13,-4,-5,-7,-6,20,21,-9,-11,-8,-10,]),'COMMA':([9,11,12,20,21,],[14,15,16,22,23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,4,],[1,10,]),'expression':([0,4,],[2,2,]),'generator':([3,14,22,23,],[6,17,24,25,]),'pairs':([3,14,22,23,],[7,7,7,7,]),'numbers':([3,14,22,23,],[8,8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> expression NEWLINE start','start',3,'p_start','Series_List_Gramar.py',54),
  ('start -> expression','start',1,'p_start','Series_List_Gramar.py',55),
  ('expression -> OPEN_BRACKET generator CLOSE_BRACKET','expression',3,'p_expression','Series_List_Gramar.py',65),
  ('generator -> pairs','generator',1,'p_generator','Series_List_Gramar.py',71),
  ('generator -> numbers','generator',1,'p_generator','Series_List_Gramar.py',72),
  ('numbers -> NUM COMMA generator','numbers',3,'p_numbers','Series_List_Gramar.py',78),
  ('numbers -> NUM','numbers',1,'p_numbers','Series_List_Gramar.py',79),
  ('pairs -> OPEN_BRACKET NUM COMMA NUM CLOSE_BRACKET COMMA generator','pairs',7,'p_pairs','Series_List_Gramar.py',88),
  ('pairs -> OPEN_BRACKET NUM COMMA NUM CLOSE_BRACKET','pairs',5,'p_pairs','Series_List_Gramar.py',89),
  ('pairs -> OPEN_BRACKET LABEL COMMA NUM CLOSE_BRACKET COMMA generator','pairs',7,'p_pairs','Series_List_Gramar.py',90),
  ('pairs -> OPEN_BRACKET LABEL COMMA NUM CLOSE_BRACKET','pairs',5,'p_pairs','Series_List_Gramar.py',91),
]
